In [ ]:
import numpy as np
from scipy import stats


In [ ]:
x = np.array([[30, 20, 40, 35, 45, 25, 50, 30], [20, 30, 50, 70, 80, 20, 90, 25], [20, 25, 20, 15, 10, 30, 10, 20]])
n = len(x[0,:])
k = len(x[:, 0])
print('n =', n, '\nk =', k)

n = 8 
k = 3


1.	Оценить параметры генеральной совокупности, которая предполагается нормально распределённой.

In [ ]:
# Находим средние значения
x1_ср = np.mean(x[0, :])
x2_ср = np.mean(x[1, :])
x3_ср = np.mean(x[2, :])
print('x1_ср =', x1_ср, '\nx2_ср =', x2_ср, '\nx3_ср =', x3_ср)

x1_ср = 34.375 
x2_ср = 48.125 
x3_ср = 18.75


In [ ]:
# Находим СКО
s1 = np.std(x[0, :])
s2 = np.std(x[1, :])
s3 = np.std(x[2, :])

print('s1 =', s1, '\ns2 =', s2, '\ns3 =', s3)

s1 = 9.499177595981665 
s2 = 26.685377550261492 
s3 = 6.49519052838329


In [ ]:
r12, p = stats.pearsonr(x[0, :], x[1, :])
r23, p = stats.pearsonr(x[1, :], x[2, :])
r13, p = stats.pearsonr(x[0, :], x[2, :])
print('r12 =', r12)
print('r23 =', r23)
print('r13 =', r13)

r12 = 0.8706610646413422
r23 = -0.8789403350824507
r13 = -0.8736977528572242


In [ ]:
x_ср = [x1_ср, x2_ср, x3_ср]
s = [s1, s2, s3]
R = [[1, r12, r13], [r12, 1, r23], [r13, r23, 1]]
print('R =')
R

R =


[[1, 0.8706610646413422, -0.8736977528572242],
 [0.8706610646413422, 1, -0.8789403350824507],
 [-0.8736977528572242, -0.8789403350824507, 1]]

2.	Найти оценку r 12/3 частного коэффициента коэффициент корреляции p 12/3 и проверить его значимость при a=0.05.

In [ ]:
R12 = np.array([[R[1][0], R[1][2]], [R[2][0], R[2][2]]])
R11 = np.array([[R[1][1], R[1][2]], [R[2][1], R[2][2]]])
R22 = np.array([[R[0][0], R[0][2]], [R[2][0], R[2][2]]])
o = np.linalg.det(R)
o1 = -np.linalg.det(R12)
o2 = np.linalg.det(R11)
o3 = np.linalg.det(R22)
print('R12 =\n', R12, 'определитель =', o1)
print('R11 =\n', R11, 'определитель =', o2)
print('R22 =\n', R22, 'определитель =', o3)

R12 =
 [[ 0.87066106 -0.87894034]
 [-0.87369775  1.        ]] определитель = -0.10273286898422934
R11 =
 [[ 1.         -0.87894034]
 [-0.87894034  1.        ]] определитель = 0.22746388736514922
R22 =
 [[ 1.         -0.87369775]
 [-0.87369775  1.        ]] определитель = 0.23665223665223678


In [ ]:
r12_3 = -o1/((o2*o3) ** 0.5)
print('r12/3 =', r12_3)

r12/3 = 0.44279007879369614


In [ ]:
from math import fabs
Tphi = fabs(r12_3)*((n-1-2)/(1-r12_3**2))**0.5
Tкр = 2.57
print('Tphi =', Tphi)

Tphi = 1.1042613956526737


In [ ]:
if Tphi < Tкр:
  print('принимается гипотеза Н0, т.е. коэффициент корреляции является незначимым')
else:
  print('принимается гипотеза Н1, т.е. коэффициент корреляции является значимым')

принимается гипотеза Н0, т.е. коэффициент корреляции является незначимым


3.	Найти точечную оценку r 1/23 множественного коэффициента корреляции p 1/23 и проверить его значимость при a=0.05.

In [ ]:
r1_23 = (1-o/o2) ** 0.5
r1_23

0.8998591687441375

In [ ]:
Fнабл = (1/(k-1) * r1_23**2)/(1/(n-k) * (1-r1_23**2))
Fкр = 5.79
print('Fнабл =', Fнабл)

Fнабл = 10.6403643546971


In [ ]:
if Fнабл < Fкр:
  print('принимается гипотеза Н0, , множественный коэффициент корреляции значимо не отличается от 0')
else:
  print('принимается гипотеза Н1, , множественный коэффициент корреляции значимо отличается от 0')

принимается гипотеза Н1, , множественный коэффициент корреляции значимо отличается от 0


4.	Построить доверительный интервал для частного коэффициента корреляции p 
12/3 при надёжности y=0.95

In [ ]:
y = 0.95
ty = 1.96 # по таблице
r12_3a = fabs(r12_3)
z0 = 0.5*(np.log(1+r12_3a) - np.log(1-r12_3a))
z1 = z0-ty*(1/(n-1-3))**0.5
z2 = z0+ty*(1/(n-1-3))**0.5
print(r12_3a)
print(z1, '<= z <=', z2)


0.44279007879369614
-0.5043039872822328 <= z <= 1.4556960127177672


In [ ]:
Pmin = -0.462
Pmax = 0.9
print(Pmin, '<= P <=', Pmax)
print('\nПолученная интервальная оценка подтверждает вывод о \nнезначимости частного коэффициента корреляции, так как нуль \nнаходится внутри доверительного интервала. ')

-0.462 <= P <= 0.9

Полученная интервальная оценка подтверждает вывод о 
незначимости частного коэффициента корреляции, так как нуль 
находится внутри доверительного интервала. 
