In [ ]:
import numpy as np

# Массив целых чисел


In [ ]:
mas1 = np.array([13, 15, 11, 18, 20])
mas2 = np.array([24, 10, 6, 35, 9])

In [ ]:
mas1 + mas2

array([37, 25, 17, 53, 29])

In [ ]:
mas1 - mas2

array([-11,   5,   5, -17,  11])

In [ ]:
mas1 * 3, mas2 * 4

(array([39, 45, 33, 54, 60]), array([ 96,  40,  24, 140,  36]))

In [ ]:
mas1 / mas2

array([0.54166667, 1.5       , 1.83333333, 0.51428571, 2.22222222])

In [ ]:
mas1 // mas2

array([0, 1, 1, 0, 2])

In [ ]:
mas1 % mas2

array([13,  5,  5, 18,  2])

In [ ]:
mas1 ** 2
mas2 ** 0.5

array([4.89897949, 3.16227766, 2.44948974, 5.91607978, 3.        ])

# Массив строк

In [ ]:
mas1 = np.array(['Hello', 'Goodbay'], dtype = object)
mas2 = np.array(['Have a nice day!', 'Good morning'], dtype = object)

In [ ]:
mas1 + mas2

array(['HelloHave a nice day!', 'GoodbayGood morning'], dtype=object)

In [ ]:
mas1 * 2, mas2 * 3

(array(['HelloHello', 'GoodbayGoodbay'], dtype=object),
 array(['Have a nice day!Have a nice day!Have a nice day!',
        'Good morningGood morningGood morning'], dtype=object))

# Массив комплексных чисел

In [ ]:
mas1 = np.array([5+2J, 1+3J])
mas2 = np.array([7+1J, 8+2J])

In [ ]:
mas1 + mas2

array([12.+3.j,  9.+5.j])

In [ ]:
mas1 - mas2

array([-2.+1.j, -7.+1.j])

In [ ]:
mas1 * 2
mas2 * 3

array([21.+3.j, 24.+6.j])

In [ ]:
mas2 ** 2

array([48.+14.j, 60.+32.j])

In [ ]:
mas1 / mas2

array([0.74      +0.18j      , 0.20588235+0.32352941j])

In [ ]:
mas1 // mas2

array([0.+0.j, 0.+0.j])

Остаток от деления не извлекается

# 4 пункт

In [ ]:
mas0 = np.zeros(6)
mas0

array([0., 0., 0., 0., 0., 0.])

In [ ]:
mas1 = np.ones(20)
mas1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
mas1[2]

1.0

In [ ]:
mas0[-1]

0.0

In [ ]:
import random
A = [-3, 1, 5, 6 -8, -2, 5, 1, -7, 8]
A.reverse()
A

[8, -7, 1, 5, -2, -2, 5, 1, -3]

In [ ]:
sum = 0
for i in range(9):
  if A[i] > 0:
    sum += A[i]

sum

20

In [ ]:
B = ['Январь', 'Февраль', 'Март', 'Апрель','Май']
B[2], B[3], B[4]

('Март', 'Апрель', 'Май')