In [ ]:
import numpy as np
from numpy import random

In [ ]:
n = 30
buyers = np.floor(random.normal(1000, 100, n))
number_of_purchases = buyers//100 + random.randint(-20, 20, 1)

In [ ]:
# max and min values
print('Максимальные значения:')
print('посетители =', max(buyers))
print('покупки =', max(number_of_purchases))
print('\nМинимальные значения:')
print('посетители =', min(buyers))
print('покупки =', min(number_of_purchases))

Максимальные значения:
посетители = 1280.0
покупки = 7.0

Минимальные значения:
посетители = 797.0
покупки = 2.0


In [ ]:
print('Для количества посетителей:')
print('среднее =', np.mean(buyers))
print('медиана =', np.median(buyers))
print('дисперсия =', np.var(buyers))
print('стандартное отклонение =', np.std(buyers))
print('\nДля числа покупок:')
print('среднее =', np.mean(number_of_purchases))
print('медиана =', np.median(number_of_purchases))
print('дисперсия =', np.var(number_of_purchases))
print('стандартное отклонение =', np.std(number_of_purchases))

Для количества посетителей:
среднее = 1042.9333333333334
медиана = 1059.5
дисперсия = 12011.662222222221
стандартное отклонение = 109.59772909245073

Для числа покупок:
среднее = 4.833333333333333
медиана = 5.0
дисперсия = 1.138888888888889
стандартное отклонение = 1.0671873729054748


In [ ]:
print('Коэффициент корреляции:')
np.corrcoef(buyers, number_of_purchases)

Коэффициент корреляции:


array([[1.        , 0.97031135],
       [0.97031135, 1.        ]])

Вывод: Коэффициент корреляции близок к 1 => сильная связь

In [ ]:
half = len(buyers)//2+1
print('посетителей в первой половине месяца было', np.sum(buyers[:half]))
print('посетителей во второй половине месяца было', np.sum(buyers[half:]))

посетителей в первой половине месяца было 16357.0
посетителей во второй половине месяца было 14931.0


Вывод: В первой половине месяца посетителей было больше

In [ ]:
for i in range (len(buyers)):
  if (i == 5) | (i == 12) | (i == 19) | (i == 26):
    print ('Посетителей в субботу было', buyers[i])
print('\n')
for i in range (len(number_of_purchases)):
  if (i == 5) | (i == 12) | (i == 19) | (i == 26):
    print ('Покупок в субботу было', number_of_purchases[i])

Посетителей в субботу было 1043.0
Посетителей в субботу было 1081.0
Посетителей в субботу было 1164.0
Посетителей в субботу было 1280.0


Покупок в субботу было 5.0
Покупок в субботу было 5.0
Покупок в субботу было 6.0
Покупок в субботу было 7.0


In [ ]:
buyers[5::7], number_of_purchases[5::7]

(array([1043., 1081., 1164., 1280.]), array([5., 5., 6., 7.]))

In [ ]:
for i in buyers[:len(buyers)]:
  if i > 1000:
    print('посетители:', i)

посетители: 1072.0
посетители: 1194.0
посетители: 1031.0
посетители: 1043.0
посетители: 1091.0
посетители: 1082.0
посетители: 1011.0
посетители: 1081.0
посетители: 1078.0
посетители: 1248.0
посетители: 1085.0
посетители: 1083.0
посетители: 1147.0
посетители: 1164.0
посетители: 1048.0
посетители: 1071.0
посетители: 1002.0
посетители: 1072.0
посетители: 1280.0
посетители: 1044.0
посетители: 1126.0


In [ ]:
print(buyers[buyers > 1000])
print('\n',buyers[(buyers < 900) & (buyers > 500)])

[1072. 1194. 1031. 1043. 1091. 1082. 1011. 1081. 1078. 1248. 1085. 1083.
 1147. 1164. 1048. 1071. 1002. 1072. 1280. 1044. 1126.]

 [840. 797. 828.]


In [ ]:
for i in buyers[:len(buyers)]:
  if (i > 10) and (i < 100):
    print('посетители:', i)

In [ ]:
print(buyers[number_of_purchases < 5])

[939. 964. 840. 968. 797. 918. 995. 986. 828.]


In [ ]:
number_of_purchases

array([5., 6., 5., 4., 4., 5., 3., 5., 5., 4., 2., 5., 5., 5., 4., 7., 5.,
       5., 6., 6., 5., 5., 5., 4., 5., 4., 7., 5., 3., 6.])

In [ ]:
buyers

array([1072., 1194., 1031.,  939.,  964., 1043.,  840., 1091., 1082.,
        968.,  797., 1011., 1081., 1078.,  918., 1248., 1085., 1083.,
       1147., 1164., 1048., 1071., 1002.,  995., 1072.,  986., 1280.,
       1044.,  828., 1126.])