In [69]:
import numpy as np
from numpy import random

In [80]:
n = 30
matrix = np.zeros((n, 2))
matrix[:,0] = buyers = np.floor(random.normal(1000, 100, n))
matrix[:,1] = buyers//100 + random.randint(-20, 20, 1)

In [81]:
# 1способ
matrix[(matrix < 0)] = 0
matrix

array([[ 951.,   24.],
       [1131.,   26.],
       [ 957.,   24.],
       [1056.,   25.],
       [ 916.,   24.],
       [ 944.,   24.],
       [1058.,   25.],
       [ 909.,   24.],
       [ 948.,   24.],
       [1061.,   25.],
       [ 981.,   24.],
       [1217.,   27.],
       [1032.,   25.],
       [ 875.,   23.],
       [ 870.,   23.],
       [ 859.,   23.],
       [1083.,   25.],
       [ 874.,   23.],
       [1022.,   25.],
       [1046.,   25.],
       [1145.,   26.],
       [1038.,   25.],
       [1004.,   25.],
       [1070.,   25.],
       [1125.,   26.],
       [1159.,   26.],
       [ 888.,   23.],
       [ 961.,   24.],
       [1058.,   25.],
       [1036.,   25.]])

In [82]:
# 2способ
for element in range (len(matrix)):
  if element < 0:
    element = 0
matrix

array([[ 951.,   24.],
       [1131.,   26.],
       [ 957.,   24.],
       [1056.,   25.],
       [ 916.,   24.],
       [ 944.,   24.],
       [1058.,   25.],
       [ 909.,   24.],
       [ 948.,   24.],
       [1061.,   25.],
       [ 981.,   24.],
       [1217.,   27.],
       [1032.,   25.],
       [ 875.,   23.],
       [ 870.,   23.],
       [ 859.,   23.],
       [1083.,   25.],
       [ 874.,   23.],
       [1022.,   25.],
       [1046.,   25.],
       [1145.,   26.],
       [1038.,   25.],
       [1004.,   25.],
       [1070.,   25.],
       [1125.,   26.],
       [1159.,   26.],
       [ 888.,   23.],
       [ 961.,   24.],
       [1058.,   25.],
       [1036.,   25.]])

In [83]:
# Округлить до целых чисел
matrix = np.floor(matrix)
matrix

array([[ 951.,   24.],
       [1131.,   26.],
       [ 957.,   24.],
       [1056.,   25.],
       [ 916.,   24.],
       [ 944.,   24.],
       [1058.,   25.],
       [ 909.,   24.],
       [ 948.,   24.],
       [1061.,   25.],
       [ 981.,   24.],
       [1217.,   27.],
       [1032.,   25.],
       [ 875.,   23.],
       [ 870.,   23.],
       [ 859.,   23.],
       [1083.,   25.],
       [ 874.,   23.],
       [1022.,   25.],
       [1046.,   25.],
       [1145.,   26.],
       [1038.,   25.],
       [1004.,   25.],
       [1070.,   25.],
       [1125.,   26.],
       [1159.,   26.],
       [ 888.,   23.],
       [ 961.,   24.],
       [1058.,   25.],
       [1036.,   25.]])

In [84]:
# Максимальное и минимальное значение
print('Максимальное значение среди покупателей', max(matrix[:, 0]))
print('Минимальное значение среди покупателей', min(matrix[:, 0]))

Максимальное значение среди покупателей 1217.0
Минимальное значение среди покупателей 859.0


In [85]:
# Максимальное и минимальное значение
print('Максимальное значение покупок', max(matrix[:, 1]))
print('Минимальное значение покупок', min(matrix[:, 1]))

Максимальное значение покупок 27.0
Минимальное значение покупок 23.0


In [86]:
# Среднее, медиана, дисперсия, СКО для покупателей
print('Для количества посетителей:')
print('среднее =', np.mean(matrix[:, 0]))
print('медиана =', np.median(matrix[:, 0]))
print('дисперсия =', np.var(matrix[:, 0]))
print('стандартное отклонение =', np.std(matrix[:, 0]))

Для количества посетителей:
среднее = 1009.1333333333333
медиана = 1027.0
дисперсия = 8785.582222222223
стандартное отклонение = 93.73143668066879


In [87]:
# Среднее, медиана, дисперсия, СКО для покупок
print('\nДля числа покупок:')
print('среднее =', np.mean(matrix[:, 1]))
print('медиана =', np.median(matrix[:, 1]))
print('дисперсия =', np.var(matrix[:, 1]))
print('стандартное отклонение =', np.std(matrix[:, 1]))


Для числа покупок:
среднее = 24.6
медиана = 25.0
дисперсия = 1.0400000000000003
стандартное отклонение = 1.019803902718557


In [116]:
# Добавить столбец
add = matrix[:, 1] * 100 // matrix[:, 0]
np.append(matrix, add)

array([ 951.,   24., 1131.,   26.,  957.,   24., 1056.,   25.,  916.,
         24.,  944.,   24., 1058.,   25.,  909.,   24.,  948.,   24.,
       1061.,   25.,  981.,   24., 1217.,   27., 1032.,   25.,  875.,
         23.,  870.,   23.,  859.,   23., 1083.,   25.,  874.,   23.,
       1022.,   25., 1046.,   25., 1145.,   26., 1038.,   25., 1004.,
         25., 1070.,   25., 1125.,   26., 1159.,   26.,  888.,   23.,
        961.,   24., 1058.,   25., 1036.,   25.,    2.,    2.,    2.,
          2.,    2.,    2.,    2.,    2.,    2.,    2.,    2.,    2.,
          2.,    2.,    2.,    2.,    2.,    2.,    2.,    2.,    2.,
          2.,    2.,    2.,    2.,    2.,    2.,    2.,    2.,    2.])

In [108]:
print('Корреляционная матрица:')
R=np.corrcoef(matrix,rowvar=False)
print(R)
print('\nКоэффициент корреляции:')
print(R[0, 1])

Корреляционная матрица:
[[1.    0.978]
 [0.978 1.   ]]

Коэффициент корреляции:
0.9780199900317771


In [110]:
print('Показатели за 5 дней:')
print('\nПокупатели', matrix[:5, 0])
print('Покупки', matrix[:5, 1])

Показатели за 5 дней:

Покупатели [ 951. 1131.  957. 1056.  916.]
Покупки [24. 26. 24. 25. 24.]


In [114]:
# 1способ
half = len(buyers)//2+1
print('посетителей в первой половине месяца было', np.sum(matrix[:half, 0]))
print('посетителей во второй половине месяца было', np.sum(matrix[half:, 0]))

посетителей в первой половине месяца было 15765.0
посетителей во второй половине месяца было 14509.0


В первой половине месяца посетителей было больше

In [128]:
for i in range (len(matrix[:, 0])):
  if (i == 5) | (i == 12) | (i == 19) | (i == 26):
    print ('Посетителей в субботу было', matrix[i, 0])
print('\n')
for i in range (len(matrix[:, 1])):
  if (i == 5) | (i == 12) | (i == 19) | (i == 26):
    print ('Покупок в субботу было', matrix[i, 1])

Посетителей в субботу было 944.0
Посетителей в субботу было 1032.0
Посетителей в субботу было 1046.0
Посетителей в субботу было 888.0


Покупок в субботу было 24.0
Покупок в субботу было 25.0
Покупок в субботу было 25.0
Покупок в субботу было 23.0
