In [ ]:
import numpy as np

In [ ]:
trud = [1, 2, 3, 4, 5, 6, 7, 8]
pism = [6, 2, 7, 4, 1, 5, 3, 8]
sobes = [1, 4, 2, 3, 6, 5, 8, 7]
n = len(sobes)

In [ ]:
# Сравниваем трудовые успехи и письменный тест
sovpad1 = np.zeros(8)
for i in range(len(pism)):
  for j in range(len(pism)):
    if i<j and pism[i] < pism[j]:
      sovpad1[i] += 1

sovpad1

array([2., 5., 1., 2., 3., 1., 1., 0.])

In [ ]:
invers1 = np.zeros(8)
for i in range(len(pism)):
  for j in range(len(pism)):
    if i<j and pism[i] > pism[j]:
      invers1[i] += 1

invers1

array([5., 1., 4., 2., 0., 1., 0., 0.])

In [ ]:
# проверка
sum(sovpad1) + sum(invers1), (n-1)*n/2

(28.0, 28.0)

In [ ]:
Temp1 = (sum(sovpad1) - sum(invers1))/((n-1)*n/2)
Temp1

0.07142857142857142

In [ ]:
Tphi1 = abs(Temp1)*((n-2)/(1-Temp1 ** 2))**0.5
Tкр = 2.306
print('Tphi1 =', Tphi1)
print('Tкр =', Tкр) 

Tphi1 = 0.17541160386140583
Tкр = 2.306


Н0: показатель корреляции значимо не отличается от нуля (является случайным).

Н1: показатель корреляции значимо отличается от нуля (является неслучайным)

Tкр > Tphi1 => приниматся гипотеза Н0

In [ ]:
# Сравниваем трудовые успехи и собеседование
sovpad2 = np.zeros(8)
for i in range(len(sobes)):
  for j in range(len(sobes)):
    if i<j and sobes[i] < sobes[j]:
      sovpad2[i] += 1

sovpad2

array([7., 4., 5., 4., 2., 2., 0., 0.])

In [ ]:
invers2 = np.zeros(8)
for i in range(len(sobes)):
  for j in range(len(sobes)):
    if i<j and sobes[i] > sobes[j]:
      invers2[i] += 1

invers2

array([0., 2., 0., 0., 1., 0., 1., 0.])

In [ ]:
# проверка
sum(sovpad2) + sum(invers2), (n-1)*n/2

(28.0, 28.0)

In [ ]:
Temp2 = (sum(sovpad2) - sum(invers2))/((n-1)*n/2)
Temp2

0.7142857142857143

In [ ]:
Tphi2 = abs(Temp2)*((n-2)/(1-Temp2 ** 2))**0.5
Tphi2

2.5

Н0: показатель корреляции значимо не отличается от нуля (является случайным).

Н1: показатель корреляции значимо отличается от нуля (является неслучайным)

Tкр < Tphi2 => принимается гипотеза Н1

**Оставляем этап собеседования**

In [ ]:
from scipy.stats import kendalltau

coef, p = kendalltau(trud, pism)
print ('coef =', coef)
print ('p =', p)

coef = 0.07142857142857142
p = 0.9048611111111111


p>0,05 => принимаем Н0

In [ ]:
coef, p = kendalltau(trud, sobes)
print ('coef =', coef)
print ('p =', p)

coef = 0.7142857142857142
p = 0.014136904761904762


p<0,05 => принимаем Н1